### ISSUE TITLE
Not getting apievents in kibana

### ISSUE THREAD

**Issue by sm0w0ms** [michaelhyatt/elastic-cloudhub-observability#7]
Hii, I am getting cloudhub logs and worker stats but did get and apievents and filebeats can you help me

**Comment by michaelhyatt** [comment]
Are you getting any errors? You can debug it further by commenting out the pipelines that work and focusing on the ones that don't in `config/pipelines.yml`

**Comment by sm0w0ms** [comment]
So in the api-events pipeline I am not getting any errors but, as per the configuration it should a create a index name api-events but it creating only creates this indexs 
![image](https://user-images.githubusercontent.com/104065050/170657790-a6a65f7c-b227-4fbc-ab4c-e3d24636e861.png)

**Comment by sm0w0ms** [comment]
And also i did found this api "https://anypoint.mulesoft.com/cloudhub/api/v2/applications/%{app_name}/dashboardStats" doc can you provide me the link.

Thank you :D

**Comment by michaelhyatt** [comment]
> And also i did found this api "[https://anypoint.mulesoft.com/cloudhub/api/v2/applications/%{app_name}/dashboardStats](https://anypoint.mulesoft.com/cloudhub/api/v2/applications/%%7Bapp_name%7D/dashboardStats)" doc can you provide me the link.
> 
> Thank you :D
Are you after the API description?

https://anypoint.mulesoft.com/exchange/portals/anypoint-platform/f1e97bc6-315a-4490-82a7-23abe036327a.anypoint-platform/cloudhub-api/minor/1.0/console/endpoint/%232219/

**Comment by michaelhyatt** [comment]
> So in the api-events pipeline I am not getting any errors but, as per the configuration it should a create a index name api-events but it creating only creates this indexs ![image](https://user-images.githubusercontent.com/104065050/170657790-a6a65f7c-b227-4fbc-ab4c-e3d24636e861.png)

Can you try and see that if you send the api-events output to the console, you see the events reported?

If there are events, then create the index manually. If there are no events, then the CloudHub API is not reporting events and there is something else going on there with your Mule app.
